  0%|                                                                                         | 0/70000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "main.py", line 43, in <module>
    trainer.train(resume_from_checkpoint = False)
  File "/home/ruihan/anaconda3/envs/or/lib/python3.7/site-packages/transformers/trainer.py", line 1504, in train
    ignore_keys_for_eval=ignore_keys_for_eval,
  File "/home/ruihan/anaconda3/envs/or/lib/python3.7/site-packages/transformers/trainer.py", line 1742, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/ruihan/anaconda3/envs/or/lib/python3.7/site-packages/transformers/trainer.py", line 2486, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/ruihan/or/Differentiable-ROUGE-score/trainer.py", line 9, in compute_loss
    outputs = model(input_ids = inputs['input_ids'].cuda(), attention_mask = inputs['attention_mask'].cuda())
  File "/home/ruihan/anaconda3/envs/or/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ruihan/anaconda3/envs/or/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 167, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/ruihan/anaconda3/envs/or/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 177, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/ruihan/anaconda3/envs/or/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/ruihan/anaconda3/envs/or/lib/python3.7/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/ruihan/anaconda3/envs/or/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/ruihan/anaconda3/envs/or/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ruihan/anaconda3/envs/or/lib/python3.7/site-packages/transformers/models/roberta/modeling_roberta.py", line 1105, in forward
    prediction_scores = self.lm_head(sequence_output)
  File "/home/ruihan/anaconda3/envs/or/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ruihan/anaconda3/envs/or/lib/python3.7/site-packages/transformers/models/roberta/modeling_roberta.py", line 1142, in forward
    x = self.decoder(x)
  File "/home/ruihan/anaconda3/envs/or/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ruihan/anaconda3/envs/or/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 94, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/ruihan/anaconda3/envs/or/lib/python3.7/site-packages/torch/nn/functional.py", line 1753, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: CUDA out of memory. Tried to allocate 2.09 GiB (GPU 0; 10.76 GiB total capacity; 8.63 GiB already allocated; 444.94 MiB free; 8.98 GiB reserved in total by PyTorch)